# Generated by Django 5.0.7 on 2024-08-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
