# Generated by Django 5.0.7 on 2024-07-23 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mental', '0002_rename_first_name_therapistprofile_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapistprofile',
            old_name='experience_years',
            new_name='experience',
        ),
    ]
