# Generated by Django 5.0.7 on 2024-07-23 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental', '0003_rename_experience_years_therapistprofile_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistprofile',
            name='email',
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='languages_spoken',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('Luganda', 'Luganda')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='specialization',
            field=models.CharField(choices=[('Psychologist', 'Psychologist'), ('Psychiatrist', 'Psychiatrist'), ('Counselor', 'Counselor')], max_length=100),
        ),
    ]
