# Generated by Django 5.0.7 on 2024-07-28 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mental', '0007_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='slug',
        ),
    ]
