# Generated by Django 5.0.7 on 2024-07-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_customuser_patientprofile_therapistprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='user',
        ),
    ]
