# Generated by Django 5.0.7 on 2024-07-23 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_customuser_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='patient',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='current_medication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TherapistProfile',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
